bool changed
int32 x_init
int32 y_init
int32 algorithm
float64  seconds
float64 speedL
float64 speedR
float64 steer_sensor
---
float64 x
float64 y
float64 steer_comput
float64 vx
float64 vy
float64 vt